const MODS={1:'Mathematics',2:'Physics',3:'Electrical Fundamentals',4:'Electronic Fundamentals',5:'Digital Techniques / Electronic Instrument Systems',6:'Materials and Hardware',7:'Maintenance Practices',8:'Basic Aerodynamics',9:'Human Factors',10:'Aviation Legislation',11:'Aeroplane Aerodynamics, Structures and Systems',12:'Helicopter Aerodynamics, Structures and Systems',13:'Aircraft Aerodynamics, Structures and Systems',14:'Propulsion',15:'Gas Turbine Engines',16:'Piston Engines',17:'Propellers',18:'Electric Power Plant','1L':'Basic Knowledge','2L':'Human Factors','3L':'Aviation Legislation','4L':'Wooden / Metal-Tube & Fabric Structure','5L':'Composite Structure','6L':'Metallic Structure','7L':'Airframe – General, Mechanical & Electrical Systems','8L':'Power Plant','9L':'Hot-Air Balloons','10L':'Gas Balloons','11L':'Airships – Hot-Air / Gas','12L':'Radio Com / ELT / Transponder / Instruments'};
const LICENCES={
'A1':{name:'A1',desc:'Turbine Aeroplanes',mods:[1,2,3,5,6,7,8,9,10,11,15,17]},'A2':{name:'A2',desc:'Piston Aeroplanes',mods:[1,2,3,5,6,7,8,9,10,11,16,17]},'A3':{name:'A3',desc:'Turbine Helicopters',mods:[1,2,3,5,6,7,8,9,10,12,15]},'A4':{name:'A4',desc:'Piston Helicopters',mods:[1,2,3,5,6,7,8,9,10,12,16]},
'B1.E':{name:'B1.E',desc:'Aeroplanes with Electric Power Plant',mods:[1,2,3,4,5,6,7,8,9,10,11,18]},'B1.1':{name:'B1.1',desc:'Turbine Aeroplanes',mods:[1,2,3,4,5,6,7,8,9,10,11,15,17],full:true},'B1.2':{name:'B1.2',desc:'Piston Aeroplanes',mods:[1,2,3,4,5,6,7,8,9,10,11,16,17]},'B1.3':{name:'B1.3',desc:'Turbine Helicopters',mods:[1,2,3,4,5,6,7,8,9,10,12,15]},'B1.4':{name:'B1.4',desc:'Piston Helicopters',mods:[1,2,3,4,5,6,7,8,9,10,12,16]},
'B2':{name:'B2',desc:'Avionics',mods:[1,2,3,4,5,6,7,8,9,10,13,14]},'B2L':{name:'B2L',desc:'Limited Avionics / System Ratings',mods:[1,2,3,4,5,6,7,8,9,10,13]},'B3':{name:'B3',desc:'Non-pressurised aeroplanes ≤ 2,000 kg MTOM',mods:[1,2,3,4,5,6,7,8,9,10,11,16,17]},
'L1C':{name:'L1C',desc:'Composite Sailplanes',mods:['1L','2L','3L','5L','7L','12L']},'L1':{name:'L1',desc:'Sailplanes',mods:['1L','2L','3L','4L','5L','6L','7L','12L']},'L2C':{name:'L2C',desc:'Composite Powered Sailplanes / ELA1',mods:['1L','2L','3L','5L','7L','8L','12L']},'L2':{name:'L2',desc:'Powered Sailplanes / ELA1',mods:['1L','2L','3L','4L','5L','6L','7L','8L','12L']},'L3H':{name:'L3H',desc:'Hot-air Balloons',mods:['1L','2L','3L','9L','12L']},'L3G':{name:'L3G',desc:'Gas Balloons',mods:['1L','2L','3L','10L','12L']},'L4H':{name:'L4H',desc:'Hot-air Airships',mods:['1L','2L','3L','8L','9L','11L','12L']},'L4G':{name:'L4G',desc:'ELA2 Gas Airships',mods:['1L','2L','3L','8L','10L','11L','12L']},'L5':{name:'L5',desc:'Gas Airships other than ELA2',mods:[1,2,3,4,5,6,7,8,9,10,11,13,14,15,16,17,'8L','10L','11L','12L']},'C':{name:'C',desc:'Base Maintenance – B1/B2 knowledge route',mods:[1,2,3,4,5,6,7,8,9,10,11,13,14,15,16,17]}}
const selectedLicence=()=>localStorage.getItem('licence')||'';
const profileKey=(part)=>`easa66:${selectedLicence()||'unselected'}:${part}`;
let SETTINGS={timer:75,length:20,passMark:75};
const S={questions:[],tab:'home',favorites:new Set(),favoriteBank:{},mistakes:new Set(),mistakeBank:{},stats:{},session:null,showLicenceSelector:true};
function loadLicenceState(){let raw={};try{raw=JSON.parse(localStorage.getItem(profileKey('settings'))||'{}')}catch{} SETTINGS=Object.assign({timer:75,length:20,passMark:75},raw);try{S.favorites=new Set(JSON.parse(localStorage.getItem(profileKey('favorites'))||'[]'))}catch{S.favorites=new Set()}try{S.favoriteBank=JSON.parse(localStorage.getItem(profileKey('favoriteBank'))||'{}')||{}}catch{S.favoriteBank={}}try{S.mistakes=new Set(JSON.parse(localStorage.getItem(profileKey('mistakes'))||'[]'))}catch{S.mistakes=new Set()}try{S.mistakeBank=JSON.parse(localStorage.getItem(profileKey('mistakeBank'))||'{}')||{}}catch{S.mistakeBank={}}try{S.stats=JSON.parse(localStorage.getItem(profileKey('stats'))||'{}')||{}}catch{S.stats={}}}
loadLicenceState();
const licence=()=>LICENCES[selectedLicence()]||LICENCES['B1.1'];
const activeMods=()=>licence().mods;
const activeQuestions=()=>S.questions.filter(q=>activeMods().map(String).includes(String(q.module)) && (!q.applicableLicences?.length || q.applicableLicences.includes(selectedLicence()) || (selectedLicence()==='C' && q.applicableLicences.some(x=>String(x).startsWith('B')))));
function chooseLicence(code){localStorage.setItem('licence',code);loadLicenceState();S.session=null;S.tab='home';S.showLicenceSelector=false;render();window.scrollTo(0,0)}

function changeLicence(){S.session=null;S.tab='home';S.showLicenceSelector=true;render();window.scrollTo(0,0)}
function licenceSnapshot(){let t=totals(),avg=t.a?Math.round(t.c/t.a*100):0;return {avg,review:S.mistakes.size,favs:S.favorites.size,attempts:t.a}}
function licenceSelector(){let groups=[['Category A',['A1','A2','A3','A4']],['Category B1',['B1.1','B1.2','B1.3','B1.4','B1.E']],['Avionics / Light',['B2','B2L','B3']],['Category L',['L1C','L1','L2C','L2','L3H','L3G','L4H','L4G','L5']],['Category C',['C']]];return `<h1>Choose your Part-66 licence</h1><div class="selectorIntro">Select the course you are preparing for. You can change it later in Settings.</div>${groups.map(g=>`<h3>${g[0]}</h3><div class="licGrid">${g[1].map(k=>{let x=LICENCES[k];return `<button class="licCard ${x.full?'full':''}" data-action="chooseLicence" data-code="${k}"><b>${x.name}</b><span>${x.desc}</span><small>${x.full?'Full B1.1 bank + dynamic engine':'Matrix-aware bank + dynamic engine'}</small></button>`}).join('')}</div>`).join('')}<div class="disclaimer">Security + Review Fix edition: expanded original scenario banks are included for M12, M13, M14, M16 and Category L modules, with troubleshooting, component function, cause/effect and maintenance-action questions. Content is independent and is not copied from commercial question banks.</div>`}
const conceptKey=q=>q.conceptId||`${q.module}|${q.chapter||''}|${q.subtopic||''}|${q.question}`;
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function save(){localStorage.setItem(profileKey('settings'),JSON.stringify(SETTINGS));localStorage.setItem(profileKey('favorites'),JSON.stringify([...S.favorites]));localStorage.setItem(profileKey('favoriteBank'),JSON.stringify(S.favoriteBank));localStorage.setItem(profileKey('mistakes'),JSON.stringify([...S.mistakes]));localStorage.setItem(profileKey('mistakeBank'),JSON.stringify(S.mistakeBank));localStorage.setItem(profileKey('stats'),JSON.stringify(S.stats))}
function normalize(q){let answers=Array.isArray(q.answers)&&q.answers.length?q.answers:(Array.isArray(q.answersIt)?q.answersIt:[]);return {...q,id:String(q.id||''),question:String(q.question||q.questionIt||''),answers:answers.map(String).slice(0,4),correct:Number(q.correct),explanation:String(q.explanation||q.explanationIt||'')}}
function validQuestion(q){return !!q&&q.id&&q.question&&Array.isArray(q.answers)&&q.answers.length>=3&&Number.isInteger(q.correct)&&q.correct>=0&&q.correct<q.answers.length&&q.module!=null}
function shuffle(a){let x=[...a];for(let i=x.length-1;i>0;i--){let j=Math.floor(Math.random()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function uniqueConcepts(items){let seen=new Set();return items.filter(q=>{let k=conceptKey(q);if(seen.has(k))return false;seen.add(k);return true})}
function unseenPool(n=20){return shuffle(uniqueConcepts(activeQuestions().filter(q=>!(S.stats[q.id]?.attempts>0)))).slice(0,n)}
function weakPool(n=20){let pool=uniqueConcepts(activeQuestions().filter(q=>S.stats[q.id]?.attempts>0));pool.sort((a,b)=>{let A=S.stats[a.id],B=S.stats[b.id],sa=(A.correct||0)/(A.attempts||1),sb=(B.correct||0)/(B.attempts||1);return sa-sb||(A.lastSeen||0)-(B.lastSeen||0)});return pool.slice(0,n)}
function adaptivePool(n=20){let now=Date.now(),pool=uniqueConcepts(activeQuestions());pool.sort((a,b)=>score(b,now)-score(a,now));return pool.slice(0,n)}
function score(q,now){let x=S.stats[q.id];if(!x)return 1000+Math.random()*20;let acc=(x.correct||0)/(x.attempts||1),age=Math.min(30,(now-(x.lastSeen||0))/86400000);return (1-acc)*500+age*8+Math.max(0,3-(x.attempts||0))*35+(q.difficulty||1)*5}
function go(tab){S.tab=tab;S.session=null;render();window.scrollTo(0,0)}
function setTabs(){document.querySelectorAll('#tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===S.tab));}
function card(icon,title,sub,action){return `<div class="card" data-action="${action}"><div class="ico">${icon}</div><div class="grow"><strong>${title}</strong><small>${sub}</small></div><b>›</b></div>`}
function home(){if(S.showLicenceSelector||!selectedLicence())return licenceSelector();let L=licence(),t=totals(),p=t.a?Math.round(t.c/t.a*100):0,aq=activeQuestions();return `<h1>EASA66 Quiz</h1><div class="hero"><img src="pilot.png"><div class="heroText"><b>EASA Part-66 Quiz</b><small>${L.name} • ${L.desc}</small></div></div><button class="licSwitch" data-action="changeLicence">Change licence / course</button><div class="stats3 homeStats"><div class="statCard"><b>${p}%</b><small>Accuracy</small></div><div class="statCard"><b>${reviewItems().length}</b><small>Review</small></div><div class="statCard"><b>${S.favorites.size}</b><small>Favourites</small></div></div>${card('▣','Study by module',`${L.mods.length} modules • ${aq.length} dedicated questions`,'go-study')}${card('⚡','Quick quiz',`${SETTINGS.length} questions • dynamic sessions`,'startQuiz')}${card('◎','Smart review','Errors, weak areas and unseen questions','startAdaptive')}${card('◷','Exam simulation',`${SETTINGS.timer}s/question • pass mark ${SETTINGS.passMark}%`,'examSetup')}${card('⚙','Profile & settings','Licence, timer, quiz length and pass mark','settingsScreen')}<div class="install">iPhone: Safari → Share → Add to Home Screen. Android: Chrome → Install app.</div>`}
function statModule(id,x){if(x&&x.module!=null)return String(x.module);let q=S.questions.find(q=>q.id===id);if(q)return String(q.module);let m=String(id).match(/^DYN-([^-]+)-/);return m?String(m[1]):''}
function moduleMetrics(n){let qs=activeQuestions().filter(q=>String(q.module)===String(n)),bankConcepts=new Set(qs.map(q=>conceptKey(q))),attempts=0,correct=0,wrong=0,seen=new Set();Object.entries(S.stats).forEach(([id,x])=>{if(statModule(id,x)!==String(n))return;attempts+=x.attempts||0;correct+=x.correct||0;wrong+=x.wrong||0;let k=x.conceptKey||id;if((x.attempts||0)>0&&bankConcepts.has(k))seen.add(k)});let accuracy=attempts?Math.round(correct/attempts*100):0;let target=Math.max(1,bankConcepts.size);let coverage=Math.min(100,Math.round(seen.size/target*100));return {bank:qs.length,target,attempts,correct,wrong,seen:seen.size,accuracy,coverage}}
function study(){let L=licence();return `<h1>Study • ${L.name}</h1><a class="sourceCard" href="https://www.easa.europa.eu/en/document-library/easy-access-rules/online-publications/easy-access-rules-continuing-airworthiness" target="_blank" rel="noopener"><b>Official EASA source</b><small>Easy Access Rules for Continuing Airworthiness ↗</small></a>${activeMods().map(n=>{let m=moduleMetrics(n),c=m.bank;return `<div class="module ${c?'':'dim'}" ${c?`data-action="startModule" data-module="${esc(n)}"`:''}><div class="m">${String(n).endsWith('L')?n:'M'+n}</div><div class="grow"><b>${MODS[n]||'Licence-specific module'}</b><div class="muted">${c?c+' bank questions':'Dedicated bank expansion pending'}</div><div class="progress"><i data-progress="${m.coverage}"></i></div><small class="muted">${m.attempts} answers • ${m.wrong} errors${m.attempts?' • '+m.accuracy+'% accuracy':''}</small></div><b>${c?(m.attempts?m.coverage+'% studied':'›'):'—'}</b></div>`}).join('')}`}
function quick(){return `<h1>Quiz • ${licence().name}</h1>${card('⚡','Quick quiz',`${SETTINGS.length} questions with immediate feedback`,'startQuiz')}${card('◆','Difficult questions','Difficulty level 3','startDifficult')}${card('◷','Exam simulation',`${SETTINGS.timer}s per question • pass mark ${SETTINGS.passMark}%`,'examSetup')}`}
function totals(){let a=0,c=0,w=0;Object.values(S.stats).forEach(x=>{a+=x.attempts||0;c+=x.correct||0;w+=x.wrong||0});return {a,c,w}}
function stats(){let t=totals(),p=t.a?Math.round(t.c/t.a*100):0;return `<h1>Progress</h1><div class="score"><div class="pct">${p}%</div><div class="muted">Overall accuracy</div></div><div class="stats3"><div class="statCard"><b>${t.a}</b><small>Answers</small></div><div class="statCard"><b>${t.c}</b><small>Correct</small></div><div class="statCard"><b>${t.w}</b><small>Errors</small></div></div>${activeMods().map(n=>{let m=moduleMetrics(n);return `<div class="module"><div class="m">${String(n).endsWith('L')?n:'M'+n}</div><div class="grow"><b>${MODS[n]}</b><div class="progress"><i data-progress="${m.coverage}"></i></div><small class="muted">${m.attempts} answers • ${m.wrong} errors${m.attempts?' • '+m.accuracy+'% accuracy':''}</small></div><b>${m.attempts?m.coverage+'% studied':'—'}</b></div>`}).join('')}`}
function review(){return `<h1>Review • ${licence().name}</h1>${card('◎','Smart review','Sessione adattiva su debolezze e recenza','startAdaptive')}${card('◆','Difficulty level','Select level 1, 2 or 3','difficultyScreen')}${card('◉','Unseen questions',`${activeQuestions().filter(q=>!(S.stats[q.id]?.attempts>0)).length} domande`,'startUnseen')}${card('↘','Weak areas','Domande con rendimento più basso','startWeak')}${card('⚠','Errors to review',`${reviewItems().length} domande`,'showErrors')}${card('★','Favourites',`${S.favorites.size} domande`,'showFavorites')}`}
function render(){setTabs();let v=$('#view');if(S.session)return renderSession();v.innerHTML=({home:home,study,quiz:quick,stats,review}[S.tab]||home)();applyDynamicUI()}
function reviewSnapshot(q){return {id:q.id,module:q.module,moduleName:q.moduleName,chapter:q.chapter||'',subtopic:q.subtopic||'',level:q.level||1,difficulty:q.difficulty||1,question:q.question,answers:[...(q.answers||[])],correct:q.correct,explanation:q.explanation||'',conceptId:q.conceptId||conceptKey(q),dynamic:!!q.dynamic,applicableLicences:q.applicableLicences||[selectedLicence()]}}
function record(q,sel,elapsed=0){let ok=sel===q.correct,x=S.stats[q.id]||{attempts:0,correct:0,wrong:0,totalTime:0,recoveryStreak:0};x.attempts++;x.lastSeen=Date.now();x.totalTime=(x.totalTime||0)+Math.max(0,elapsed);x.lastAnswer=sel;x.module=String(q.module);x.conceptKey=conceptKey(q);x.dynamic=!!q.dynamic;if(ok){x.correct++;if(S.mistakes.has(q.id)){x.recoveryStreak=(x.recoveryStreak||0)+1;if(x.recoveryStreak>=2){S.mistakes.delete(q.id);delete S.mistakeBank[q.id];x.recoveryStreak=0}}}else{x.wrong++;x.recoveryStreak=0;S.mistakes.add(q.id);S.mistakeBank[q.id]=reviewSnapshot(q)}x.mastery=Math.round(((x.correct||0)/(x.attempts||1))*100);S.stats[q.id]=x;save();return ok}
function startModule(n){start(S.questions.filter(q=>q.module==n),`M${n} – ${MODS[n]}`,false)}
function startQuiz(){start(shuffle(uniqueConcepts(activeQuestions())).slice(0,SETTINGS.length),'Quiz rapido',false)}
function difficultyScreen(){S.session=null;let aq=activeQuestions();let count=l=>aq.filter(q=>Number(q.difficulty||1)===l).length;$('#view').innerHTML=`<button class="back" data-action="go-review">‹ Back</button><h1>Difficulty • ${licence().name}</h1><div class="selectorIntro">Choose the difficulty for this review session. This is separate from the EASA Knowledge Level 1/2/3 shown on each question.</div>${card('◇','Difficulty 1 – Foundation',`${count(1)} questions`,'difficulty1')}${card('◆','Difficulty 2 – Applied',`${count(2)} questions`,'difficulty2')}${card('⬢','Difficulty 3 – Advanced',`${count(3)} questions`,'difficulty3')}${card('◎','Mixed difficulty',`${aq.length} questions across levels 1–3`,'difficultyMixed')}`}
function startDifficulty(level=null){let pool=activeQuestions().filter(q=>level==null||Number(q.difficulty||1)===Number(level));let x=shuffle(uniqueConcepts(pool)).slice(0,SETTINGS.length);if(!x.length)return listQuestions(level==null?'Mixed difficulty':`Difficulty ${level}`,[]);start(x,level==null?'Mixed difficulty':`Difficulty ${level}`,false)}
function startDifficult(){startDifficulty(3)}
function startAdaptive(){let x=adaptivePool(SETTINGS.length);if(!x.length)x=shuffle(uniqueConcepts(activeQuestions())).slice(0,SETTINGS.length);start(x,'Smart review',false)}
function startUnseen(){let x=unseenPool(SETTINGS.length);if(!x.length)return listQuestions('Unseen questions',[]);start(x,'Domande mai viste',false)}
function startWeak(){let x=weakPool(SETTINGS.length);if(!x.length)return listQuestions('Weak areas',[]);start(x,'Weak areas',false)}
function start(items,title,exam){S.session={items:uniqueConcepts(items),title,exam,index:0,selected:null,checked:false,answers:[],seconds:SETTINGS.timer,timer:null,finished:false,questionStarted:Date.now()};renderSession();if(exam)tick()}
function renderSession(){let s=S.session,v=$('#view');if(!s)return render();if(s.finished||s.index>=s.items.length){return result()}let q=s.items[s.index],pct=s.index/Math.max(1,s.items.length)*100;v.innerHTML=`<button class="back" data-action="stopSession">‹ Indietro</button><div class="qtop"><span>M${q.module} • ${esc(q.chapter)}</span><span>${s.index+1}/${s.items.length}</span></div><div class="progress"><i data-progress="${pct}"></i></div>${s.exam?`<div class="timer ${s.seconds<=15?'red':''}"><b>◷ ${s.seconds}s</b><div class="progress grow"><i data-progress="${s.seconds/SETTINGS.timer*100}"></i></div></div>`:''}<div class="chips"><span class="chip">Livello EASA ${q.level}</span><span class="chip">Difficoltà ${q.difficulty}</span></div><div class="question">${esc(q.question)}</div>${q.answers.map((a,i)=>answerHtml(q,i,a)).join('')}${s.checked&&!s.exam?`<div class="feedback ${s.selected===q.correct?'ok':'no'}"><b>${s.selected===q.correct?'Risposta corretta':'Risposta errata'}</b><div>${esc(q.explanation)}</div></div>`:''}<div class="actions"><button class="btn" data-action="toggleFav" data-id="${esc(q.id)}">${S.favorites.has(q.id)?'★ Preferita':'☆ Salva'}</button><button class="btn primary" ${s.selected==null&&!s.checked?'disabled':''} data-action="advance">${s.exam?'Conferma':s.checked?'Successiva':'Conferma'}</button></div>`;applyDynamicUI()}
function answerHtml(q,i,a){let s=S.session,cls='';if(s.selected===i)cls=' selected';if(s.checked&&!s.exam){if(i===q.correct)cls=' correct';else if(i===s.selected)cls=' wrong'}return `<button class="answer${cls}" data-action="selectAnswer" data-index="${i}"><span class="letter">${['A','B','C','D'][i]||i+1}</span><span>${esc(a)}</span></button>`}
function selectAnswer(i){let s=S.session;if(!s||s.checked)return;s.selected=i;if(!s.exam){s.checked=true;record(s.items[s.index],i,Math.round((Date.now()-s.questionStarted)/1000))}renderSession()}
function advance(timed=false){let s=S.session,q=s.items[s.index];if(s.exam){let sel=timed?null:s.selected;if(sel==null&&!timed)return;let ok=record(q,sel,Math.round((Date.now()-s.questionStarted)/1000));s.answers.push({q,selected:sel,ok})}else if(s.checked){s.answers.push({q,selected:s.selected,ok:s.selected===q.correct})}else return;clearInterval(s.timer);s.timer=null;s.selected=null;s.checked=false;if(s.index+1>=s.items.length){s.finished=true;result()}else{s.index++;s.seconds=SETTINGS.timer;s.questionStarted=Date.now();renderSession();if(s.exam)tick()}}
function tick(){let s=S.session;clearInterval(s.timer);s.timer=setInterval(()=>{if(!S.session||S.session!==s){clearInterval(s.timer);return}s.seconds--;if(s.seconds<=0){clearInterval(s.timer);advance(true)}else renderSession()},1000)}
function stopSession(){if(S.session?.timer)clearInterval(S.session.timer);S.session=null;render()}
function result(){let s=S.session,a=s.answers,c=a.filter(x=>x.ok).length,p=a.length?Math.round(c/a.length*100):0,pass=p>=SETTINGS.passMark;let mods=[...new Set(a.map(x=>x.q.module))].sort((x,y)=>x-y);$('#view').innerHTML=`<button class="back" data-action="stopSession">‹ Home</button><div class="score"><div class="scoreIcon">${pass?'✓':'✕'}</div><h2>${s.exam?(pass?'Esame superato':'Esame non superato'):'Quiz completato'}</h2><div class="pct ${s.exam?(pass?'pass':'fail'):''}">${p}%</div><div class="muted">${c} corrette su ${a.length} • pass mark ${SETTINGS.passMark}%</div></div>${mods.map(m=>{let x=a.filter(z=>z.q.module===m),cc=x.filter(z=>z.ok).length,pp=x.length?Math.round(cc/x.length*100):0;return `<div class="module"><b>M${m}</b><span>${cc}/${x.length}</span><span class="grow"></span><b>${pp}%</b></div>`}).join('')}${a.some(x=>!x.ok)?`<button class="btn primary" data-action="sessionErrors">Rivedi gli errori</button>`:''}`;applyDynamicUI()}
function sessionErrors(){let bad=S.session.answers.filter(x=>!x.ok);listQuestions('Errori sessione',bad.map(x=>x.q),true)}
function toggleFav(id){let q=S.session?.items?.find(x=>x.id===id)||S.questions.find(x=>x.id===id)||S.favoriteBank[id];if(S.favorites.has(id)){S.favorites.delete(id);delete S.favoriteBank[id]}else{S.favorites.add(id);if(q)S.favoriteBank[id]=reviewSnapshot(q)}save();renderSession()}
function reviewItems(){let out=[];for(const id of S.mistakes){let q=S.mistakeBank[id]||S.questions.find(x=>x.id===id);if(q)out.push(q)}return uniqueConcepts(out)}
function syncReviewStore(){let changed=false;for(const id of [...S.mistakes]){if(!S.mistakeBank[id]){let q=S.questions.find(x=>x.id===id);if(q){S.mistakeBank[id]=reviewSnapshot(q);changed=true}}}if(changed)save()}
function showErrors(){syncReviewStore();let x=reviewItems();if(!x.length)return listQuestions('Errors to review',[]);start(x,'Errors to review • 2 correct answers to recover',false)}
function showFavorites(){let allowed=new Set(activeMods().map(String)),x=[];for(const id of S.favorites){let q=S.favoriteBank[id]||S.questions.find(z=>z.id===id);if(q&&allowed.has(String(q.module)))x.push(q)}x=uniqueConcepts(x);if(!x.length)return listQuestions('Favourites',[]);start(x,'Favourites',false)}
function listQuestions(title,items,showCorrect=false){S.session=null;$('#view').innerHTML=`<button class="back" data-action="go-review">‹ Indietro</button><h1>${title}</h1>${items.length?items.map(q=>`<div class="card" data-action="reviewOne" data-id="${esc(q.id)}"><div class="grow"><strong>${esc(q.question)}</strong><small>M${q.module} • ${esc(q.chapter)}</small>${showCorrect?`<div class="correctText">Corretta: ${esc(q.answers[q.correct])}</div><div class="muted">${esc(q.explanation)}</div>`:''}</div><b>›</b></div>`).join(''):`<div class="empty">Nessuna domanda presente.</div>`}`}
let EXAM_SETUP=null;
function examSetup(){S.session=null;EXAM_SETUP={count:SETTINGS.length,timer:SETTINGS.timer,pass:SETTINGS.passMark};drawExamSetup()}
function drawExamSetup(){let {count,timer,pass}=EXAM_SETUP;$('#view').innerHTML=`<button class="back" data-action="go-home">‹ Back</button><h1>Exam simulation</h1><div class="score"><div class="scoreIcon">◷</div><h2>${licence().name} – ${licence().desc}</h2></div><div class="stepper"><span>Number of questions</span><div><button data-action="exam-count" data-delta="-10">−</button> <b>${count}</b> <button data-action="exam-count" data-delta="10">+</button></div></div><div class="stepper"><span>Time per question</span><div><button data-action="exam-time" data-delta="-15">−</button> <b>${timer}s</b> <button data-action="exam-time" data-delta="15">+</button></div></div><div class="stepper"><span>Pass mark</span><div><button data-action="exam-pass" data-delta="-5">−</button> <b>${pass}%</b> <button data-action="exam-pass" data-delta="5">+</button></div></div><button class="btn primary fullWidth" data-action="exam-start">Start simulation</button>`}

function settingsScreen(){S.session=null;$('#view').innerHTML=`<button class="back" data-action="go-home">‹ Back</button><h1>Profile & settings</h1><div class="setting"><div><b>Current licence</b><small>${licence().name} • ${licence().desc}</small></div><button class="btn" data-action="changeLicence">Change</button></div><div class="setting"><div><b>Question timer</b><small>Default exam time</small></div><select data-change="timer">${[30,45,60,75,90,105,120,150,180].map(x=>`<option value="${x}" ${SETTINGS.timer==x?'selected':''}>${x}s</option>`).join('')}</select></div><div class="setting"><div><b>Pass mark</b><small>Default exam threshold</small></div><select data-change="passMark">${[50,55,60,65,70,75,80,85,90,95,100].map(x=>`<option value="${x}" ${SETTINGS.passMark==x?'selected':''}>${x}%</option>`).join('')}</select></div><div class="setting"><div><b>Quiz length</b><small>Default number of questions</small></div><select data-change="length">${[10,20,30,40,50,75,100].map(x=>`<option value="${x}" ${SETTINGS.length==x?'selected':''}>${x}</option>`).join('')}</select></div><button class="btn danger" data-action="resetProgress">Reset progress, errors and favourites</button><div class="disclaimer">Independent Part-66 study app. Not affiliated with or approved by EASA. B1.1 is the complete current content track; other licence tracks are enabled as a multi-licence framework with shared applicable core content while dedicated banks are expanded.</div>`}
function setPassMark(v){SETTINGS.passMark=Number(v);save();settingsScreen()}
function setTimer(v){SETTINGS.timer=Number(v);save()}function setLength(v){SETTINGS.length=Number(v);save()}
function resetProgress(){if(confirm('Azzera statistiche, errori e preferiti?')){S.stats={};S.mistakes.clear();S.mistakeBank={};S.favorites.clear();S.favoriteBank={};save();settingsScreen()}}
function applyDynamicUI(){document.querySelectorAll('[data-progress]').forEach(el=>{let n=Math.max(0,Math.min(100,Number(el.dataset.progress)||0));el.style.width=n+'%'})}
document.addEventListener('click',e=>{const el=e.target.closest('[data-action]');if(!el)return;const a=el.dataset.action;const actions={
'go-study':()=>go('study'),'go-review':()=>go('review'),'go-home':()=>go('home'),difficultyScreen,difficulty1:()=>startDifficulty(1),difficulty2:()=>startDifficulty(2),difficulty3:()=>startDifficulty(3),difficultyMixed:()=>startDifficulty(null),chooseLicence:()=>chooseLicence(el.dataset.code),changeLicence,settingsScreen,startQuiz,startAdaptive,startDifficult,startUnseen,startWeak,showErrors,showFavorites,examSetup,stopSession,advance,sessionErrors,resetProgress,
startModule:()=>startModule(el.dataset.module),selectAnswer:()=>selectAnswer(Number(el.dataset.index)),toggleFav:()=>toggleFav(el.dataset.id),reviewOne:()=>{let q=S.mistakeBank[el.dataset.id]||S.favoriteBank[el.dataset.id]||S.questions.find(x=>x.id===el.dataset.id);if(q)start([q],'Ripasso',false)},
'exam-count':()=>{EXAM_SETUP.count=Math.max(10,Math.min(100,EXAM_SETUP.count+Number(el.dataset.delta)));drawExamSetup()},
'exam-time':()=>{EXAM_SETUP.timer=Math.max(30,Math.min(180,EXAM_SETUP.timer+Number(el.dataset.delta)));drawExamSetup()},
'exam-pass':()=>{EXAM_SETUP.pass=Math.max(50,Math.min(100,EXAM_SETUP.pass+Number(el.dataset.delta)));drawExamSetup()},
'exam-start':()=>{SETTINGS.timer=EXAM_SETUP.timer;SETTINGS.passMark=EXAM_SETUP.pass;SETTINGS.length=EXAM_SETUP.count;save();start(buildDynamicQuiz(EXAM_SETUP.count),'Exam simulation',true)}
};if(actions[a])actions[a]()});
document.addEventListener('change',e=>{let k=e.target.dataset.change;if(k==='timer')setTimer(e.target.value);else if(k==='passMark')setPassMark(e.target.value);else if(k==='length')setLength(e.target.value)});
document.querySelectorAll('#tabs button').forEach(b=>b.addEventListener('click',()=>go(b.dataset.tab)));
fetch('questions.json').then(r=>r.json()).then(q=>{S.questions=(Array.isArray(q)?q:[]).map(normalize).filter(validQuestion);syncReviewStore();setTimeout(()=>{$('#splash').remove();$('#app').classList.remove('hidden');render()},1800)}).catch(e=>{$('#splash').innerHTML='<div class="loadError">Errore caricamento banca domande.</div>'});
if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));

// v1.3 Dynamic Quiz Engine
function dynHistory(){try{return JSON.parse(localStorage.getItem(profileKey('dynamicHistory'))||'[]')}catch{return []}}
function saveDynHistory(sig){let h=dynHistory();h.unshift({sig,t:Date.now()});localStorage.setItem(profileKey('dynamicHistory'),JSON.stringify(h.slice(0,500)))}
function ri(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function pick(a){return a[Math.floor(Math.random()*a.length)]}
function gcd(a,b){while(b){[a,b]=[b,a%b]}return Math.abs(a)}
function numericDistractors(correct,step=1){let vals=new Set([correct]);let tries=0;while(vals.size<3&&tries++<30){let d=pick([-3,-2,-1,1,2,3])*step;let v=correct+d;if(v>0)vals.add(v)}return [...vals]}
function makeOptions(correct,wrong,fmt=x=>String(x)){let raw=[correct,...wrong.filter(x=>x!==correct).slice(0,2)];while(raw.length<3)raw.push(correct+raw.length+1);let sh=shuffle(raw),idx=sh.indexOf(correct);return {answers:sh.map(fmt),correct:idx}}
function dynBase(module,chapter,subtopic,level,difficulty,question,answers,correct,explanation,conceptId){let nonce=`${Date.now()}-${Math.random().toString(36).slice(2,8)}`;return {id:`DYN-${module}-${nonce}`,module,moduleName:MODS[module],chapter,subtopic,level,difficulty,question,answers,correct,explanation,quality:'dynamic-validated',conceptId:`DYN-${conceptId}-${nonce}`,dynamic:true}}
function genMath(){let kind=ri(1,5);
if(kind===1){let a=ri(4,14),b=ri(2,9),c=ri(2,7),ans=a+b*c;let o=makeOptions(ans,[(a+b)*c,a*b+c,ans+b]);return dynBase(1,'Mathematics','Order of operations',2,2,`Evaluate ${a} + ${b} × ${c}.`,o.answers,o.correct,`Multiplication is performed first: ${b} × ${c} = ${b*c}; then ${a} + ${b*c} = ${ans}.`,'order-operations')}
if(kind===2){let base=pick([80,120,160,200,240,320]),p=pick([10,15,20,25]),inc=base*p/100,ans=base+inc;let o=makeOptions(ans,[base-inc,inc,base+p]);return dynBase(1,'Mathematics','Percentages',2,2,`A component mass is ${base} g. It increases by ${p}%. What is the new mass?`,o.answers,o.correct,`${p}% of ${base} g is ${inc} g; therefore the new mass is ${base} + ${inc} = ${ans} g.`,'percentage-increase')}
if(kind===3){let x=ri(3,12),a=ri(2,7),b=ri(2,15),rhs=a*x+b;let o=makeOptions(x,[x+1,Math.max(1,x-1),a*x]);return dynBase(1,'Mathematics','Algebra',2,2,`Solve for x: ${a}x + ${b} = ${rhs}.`,o.answers,o.correct,`Subtract ${b}: ${a}x = ${rhs-b}. Divide by ${a}: x = ${x}.`,'linear-equation')}
if(kind===4){let l=ri(6,18),w=ri(3,10),cut=ri(1,Math.min(3,w-1)),ans=l*(w-cut);let o=makeOptions(ans,[l*w,l*(w+cut),(l-cut)*w],x=>`${x} m²`);return dynBase(1,'Mathematics','Geometry',2,2,`A rectangular panel is ${l} m long and ${w} m wide. A strip ${cut} m wide is removed along the full length. What area remains?`,o.answers,o.correct,`The remaining width is ${w}-${cut}=${w-cut} m, so area = ${l} × ${w-cut} = ${ans} m².`,'rectangle-remainder')}
let n=pick([3,4,5,6]),den=pick([8,10,12,16,20]),num=ri(1,den-2),add=ri(1,den-num),ans=(num+add)/den;let o=makeOptions(ans,[num/den,add/den,(num+add)/(den*2)],x=>Number(x.toFixed(3)).toString());return dynBase(1,'Mathematics','Fractions',2,2,`A tank is ${num}/${den} full and receives an additional ${add}/${den} of its total capacity. What fraction of full capacity is now occupied, expressed as a decimal?`,o.answers,o.correct,`The fractions have the same denominator: (${num}+${add})/${den} = ${num+add}/${den} = ${Number(ans.toFixed(3))}.`,'fraction-addition')}
function genPhysics(){let kind=ri(1,5);
if(kind===1){let u=pick([4,6,8,10]),a=pick([2,3,4]),t=pick([3,4,5]),v=u+a*t;let o=makeOptions(v,[u+a+t,a*t,v+a],x=>`${x} m/s`);return dynBase(2,'Physics','Kinematics',2,2,`An object starts at ${u} m/s and accelerates uniformly at ${a} m/s² for ${t} s. What is its final velocity?`,o.answers,o.correct,`v = u + at = ${u} + (${a} × ${t}) = ${v} m/s.`,'final-velocity')}
if(kind===2){let m=pick([2,3,4,5]),v=pick([4,6,8,10]),ans=0.5*m*v*v;let o=makeOptions(ans,[m*v*v,m*v,0.5*m*v],x=>`${x} J`);return dynBase(2,'Physics','Energy',2,3,`A ${m} kg component moves at ${v} m/s. What is its kinetic energy?`,o.answers,o.correct,`KE = ½mv² = 0.5 × ${m} × ${v}² = ${ans} J.`,'kinetic-energy')}
if(kind===3){let f=pick([120,180,240,300]),area=pick([20,30,40,50]),m2=area/10000,ans=f/m2;let o=makeOptions(ans,[f/area,f*area,ans/10],x=>`${Math.round(x)} Pa`);return dynBase(2,'Physics','Pressure',2,3,`A force of ${f} N acts uniformly over ${area} cm². What pressure is produced?`,o.answers,o.correct,`${area} cm² = ${m2.toFixed(4)} m². P = F/A = ${f}/${m2.toFixed(4)} = ${Math.round(ans)} Pa.`,'pressure-area-conversion')}
if(kind===4){let f=pick([100,150,200,250]),d=pick([3,4,5,6]),t=pick([5,10,12]),work=f*d,ans=work/t;let o=makeOptions(ans,[work,f/t,f*d*t],x=>`${Number(x.toFixed(1))} W`);return dynBase(2,'Physics','Work and power',2,3,`A constant force of ${f} N moves a load ${d} m in ${t} s. What average power is developed?`,o.answers,o.correct,`Work = Fd = ${f} × ${d} = ${work} J. Power = ${work}/${t} = ${Number(ans.toFixed(1))} W.`,'mechanical-power')}
let m=pick([2,3,4,5]),a=pick([2,3,4,5]),fr=pick([1,2,3,4]),applied=m*a+fr;let o=makeOptions(applied,[m*a,applied-fr,applied+fr],x=>`${x} N`);return dynBase(2,'Physics','Dynamics',2,3,`A ${m} kg unit must accelerate at ${a} m/s² while a ${fr} N resistive force opposes motion. What applied force is required?`,o.answers,o.correct,`Required net force is ma = ${m*a} N. The applied force must also overcome ${fr} N resistance: ${m*a}+${fr}=${applied} N.`,'force-with-resistance')}
function genElectrical(){let kind=ri(1,6);
if(kind===1){let r1=pick([2,4,6,8]),r2=pick([4,6,8,10]),i=pick([2,3,4]),v=i*(r1+r2);let o=makeOptions(v,[i*r1,i*r2,v+i],x=>`${x} V`);return dynBase(3,'Electrical Fundamentals','Series circuits',2,2,`Two series resistors of ${r1} Ω and ${r2} Ω carry ${i} A. What supply voltage is required?`,o.answers,o.correct,`Rtotal = ${r1}+${r2}=${r1+r2} Ω. V = IR = ${i} × ${r1+r2} = ${v} V.`,'series-voltage')}
if(kind===2){let r1=pick([4,6,8,12]),r2=r1,ans=r1/2;let o=makeOptions(ans,[r1*2,r1,r1/4],x=>`${x} Ω`);return dynBase(3,'Electrical Fundamentals','Parallel circuits',2,2,`Two identical ${r1} Ω resistors are connected in parallel. What is their equivalent resistance?`,o.answers,o.correct,`For two equal resistors in parallel, equivalent resistance is half one resistor: ${r1}/2 = ${ans} Ω.`,'parallel-equal')}
if(kind===3){let v=pick([12,24,28,48]),i=pick([2,3,4,5]),t=pick([5,10,15]),p=v*i,e=p*t;let o=makeOptions(e,[p,v*t,e+i],x=>`${x} J`);return dynBase(3,'Electrical Fundamentals','Electrical energy',2,3,`A ${v} V load draws ${i} A continuously for ${t} s. How much electrical energy is consumed?`,o.answers,o.correct,`P = VI = ${v} × ${i} = ${p} W. Energy = Pt = ${p} × ${t} = ${e} J.`,'electrical-energy')}
if(kind===4){let r1=pick([2,4,6]),r2=pick([6,8,10,12]),i=pick([2,3]),v=i*(r1+r2),drop=i*r2;let o=makeOptions(drop,[i*r1,v,Math.abs(i*(r2-r1))],x=>`${x} V`);return dynBase(3,'Electrical Fundamentals','Voltage division',2,3,`Resistors ${r1} Ω and ${r2} Ω are in series across a ${v} V supply. What is the voltage drop across the ${r2} Ω resistor?`,o.answers,o.correct,`Series current = ${v}/(${r1}+${r2}) = ${i} A. The drop across ${r2} Ω is ${i} × ${r2} = ${drop} V.`,'voltage-divider')}
if(kind===5){let v=pick([12,24,28]),p=pick([24,48,56,72,84]);while(p%v!==0)p+=v-(p%v);let i=p/v,r=v/i;let o=makeOptions(r,[v*i,p/i,r+i],x=>`${Number(x.toFixed(2))} Ω`);return dynBase(3,'Electrical Fundamentals','Power and resistance',2,3,`A resistive load dissipates ${p} W from a ${v} V supply. What is its resistance?`,o.answers,o.correct,`I = P/V = ${p}/${v} = ${i} A; therefore R = V/I = ${v}/${i} = ${Number(r.toFixed(2))} Ω.`,'resistance-from-power')}
let r=pick([3,4,5,6,8]),i=pick([2,3,4]),p=i*i*r;let o=makeOptions(p,[i*r,p+i,p-r],x=>`${x} W`);return dynBase(3,'Electrical Fundamentals','Power',2,2,`A ${r} Ω resistor carries ${i} A. What power is dissipated?`,o.answers,o.correct,`P = I²R = ${i}² × ${r} = ${p} W.`,'dc-power')}

// v1.5: validated scenario generators for all remaining B1.1 modules.
function scenarioQ(m,chapter,subtopic,level,difficulty,stem,correctAnswer,wrongAnswers,explanation,concept){
  let opts=shuffle([correctAnswer,...wrongAnswers.slice(0,2)]),ci=opts.indexOf(correctAnswer);
  return dynBase(m,chapter,subtopic,level,difficulty,stem,opts,ci,explanation,concept)
}
function genM4(){let k=ri(1,3);if(k===1){let gain=pick([20,50,100]),vin=pick([10,20,40]),vout=gain*vin/1000;return scenarioQ(4,'Electronic Fundamentals','Amplifiers',2,3,`An amplifier has a voltage gain of ${gain}. An input signal of ${vin} mV is applied. Assuming linear operation, what output voltage is expected?`,`${Number(vout.toFixed(2))} V`,[`${Number((vout/gain).toFixed(2))} V`,`${Number((vin/gain).toFixed(2))} V`,`${gain*vin} V`],`Convert ${vin} mV to ${vin/1000} V and multiply by the gain: ${vin/1000} × ${gain} = ${Number(vout.toFixed(2))} V.`,'amplifier-gain')}
if(k===2){let v=pick([5,9,12,15]),drop=pick([0.6,0.7]),r=pick([470,680,1000]),i=(v-drop)/r*1000;return scenarioQ(4,'Electronic Fundamentals','Diodes',2,3,`A silicon diode with a forward drop of ${drop} V is in series with a ${r} Ω resistor across a ${v} V DC supply. Approximately what current flows?`,`${i.toFixed(1)} mA`,[`${(v/r*1000).toFixed(1)} mA`,`${(drop/r*1000).toFixed(1)} mA`,`${((v+drop)/r*1000).toFixed(1)} mA`],`The resistor sees ${v}-${drop}=${(v-drop).toFixed(1)} V. I=V/R=${(v-drop).toFixed(1)}/${r}=${i.toFixed(1)} mA.`,'diode-series-current')}
let r1=pick([1000,2200,4700]),r2=pick([1000,2200,4700]),vin=pick([5,10,12]),v=vin*r2/(r1+r2);return scenarioQ(4,'Electronic Fundamentals','Bias networks',2,3,`A divider uses ${r1} Ω from a ${vin} V supply to the output node and ${r2} Ω from the node to ground. With no load, what is the node voltage?`,`${v.toFixed(2)} V`,[`${(vin*r1/(r1+r2)).toFixed(2)} V`,`${(vin/(r1+r2)).toFixed(2)} V`,`${vin.toFixed(2)} V`],`For an unloaded divider, Vout=Vin×R2/(R1+R2)=${vin}×${r2}/${r1+r2}=${v.toFixed(2)} V.`,'bias-divider')}
function genM5(){let k=ri(1,3);if(k===1){let bits=pick([8,10,12]),levels=2**bits;return scenarioQ(5,'Digital Techniques','Data representation',2,2,`An unsigned ${bits}-bit binary word is used by a digital system. How many distinct values can it represent?`,`${levels}`,[`${levels-1}`,`${bits*2}`,`${bits**2}`],`An unsigned n-bit word has 2^n distinct combinations. For ${bits} bits, 2^${bits}=${levels}.`,'binary-levels')}
if(k===2){let f=pick([1,2,4,8]),period=1/(f*1e6)*1e6;return scenarioQ(5,'Digital Techniques','Clock signals',2,3,`A digital bus operates with a ${f} MHz clock. What is the duration of one clock period?`,`${period.toFixed(3)} µs`,[`${(period*2).toFixed(3)} µs`,`${(1/f).toFixed(3)} ms`,`${f.toFixed(3)} µs`],`T=1/f. At ${f} MHz, one period is ${period.toFixed(3)} microseconds.`,'clock-period')}
let n=pick([4,8,16]),bytes=pick([256,512,1024]),bits=bytes*8;return scenarioQ(5,'Digital Techniques','Memory',2,2,`A maintenance data block contains ${bytes} bytes. How many bits does it contain?`,`${bits} bits`,[`${bytes} bits`,`${bytes*4} bits`,`${bits/2} bits`],`Each byte contains 8 bits, so ${bytes}×8=${bits} bits.`,'bytes-to-bits')}
function genM6(){let k=ri(1,3);if(k===1){let d=pick([6,8,10,12]),area=Math.PI*d*d/4;return scenarioQ(6,'Materials and Hardware','Fasteners',2,3,`A circular fastener shank has a diameter of ${d} mm. Approximately what is its cross-sectional area?`,`${area.toFixed(1)} mm²`,[`${(Math.PI*d).toFixed(1)} mm²`,`${(d*d).toFixed(1)} mm²`,`${(area/2).toFixed(1)} mm²`],`Area of a circle is πd²/4. For d=${d} mm, A≈${area.toFixed(1)} mm².`,'fastener-area')}
if(k===2){let original=pick([100,120,150]),delta=pick([0.10,0.15,0.20]),final=original*(1+delta);return scenarioQ(6,'Materials and Hardware','Thermal expansion',2,3,`A metal component is ${original} mm long. Under the stated temperature change its length increases by ${(delta*100).toFixed(0)}%. What final length results?`,`${final.toFixed(1)} mm`,[`${(original*delta).toFixed(1)} mm`,`${(original*(1-delta)).toFixed(1)} mm`,`${(original+delta).toFixed(1)} mm`],`The increase is ${original}×${delta}=${(original*delta).toFixed(1)} mm; final length=${final.toFixed(1)} mm.`,'expansion-percent')}
let load=pick([1200,1800,2400]),area=pick([20,30,40]),stress=load/area;return scenarioQ(6,'Materials and Hardware','Mechanical properties',2,3,`A tensile load of ${load} N is carried uniformly by a ${area} mm² section. What tensile stress is produced?`,`${stress.toFixed(1)} N/mm²`,[`${(load*area).toFixed(1)} N/mm²`,`${(area/load).toFixed(3)} N/mm²`,`${(stress/2).toFixed(1)} N/mm²`],`Stress=force/area=${load}/${area}=${stress.toFixed(1)} N/mm².`,'tensile-stress')}
function genM7(){let k=ri(1,3);if(k===1){let actual=pick([24.96,49.92,74.85]),nom=actual<30?25:actual<60?50:75,tol=pick([0.2,0.3,0.5]),dev=Math.abs(actual-nom);let ok=dev<=tol;return scenarioQ(7,'Maintenance Practices','Inspection and measurement',3,3,`A shaft has a nominal diameter of ${nom.toFixed(2)} mm with an allowable deviation of ±${tol.toFixed(2)} mm. A measurement gives ${actual.toFixed(2)} mm. What is the correct maintenance assessment?`,ok?'The dimension is within tolerance':'The dimension is outside tolerance',[ok?'The dimension is outside tolerance':'The dimension is within tolerance','The part is acceptable only after lubrication'],`The measured deviation is ${dev.toFixed(2)} mm. The permitted deviation is ±${tol.toFixed(2)} mm, so the dimension is ${ok?'within':'outside'} tolerance.`,'dimensional-tolerance')}
if(k===2){let torque=pick([20,30,40,50]),ext=pick([0.20,0.25,0.30]),force=torque/ext;return scenarioQ(7,'Maintenance Practices','Torque',3,3,`A technician must apply ${torque} N·m using a wrench with an effective lever arm of ${ext.toFixed(2)} m. Ignoring losses, what perpendicular force is required?`,`${force.toFixed(0)} N`,[`${(force/2).toFixed(0)} N`,`${(torque*ext).toFixed(0)} N`,`${(force*ext).toFixed(0)} N`],`Torque=force×lever arm, so force=${torque}/${ext.toFixed(2)}=${force.toFixed(0)} N.`,'torque-force')}
let interval=pick([400,500,600]),used=pick([120,180,250]),remain=interval-used;return scenarioQ(7,'Maintenance Practices','Maintenance planning',3,2,`A component has a scheduled inspection interval of ${interval} flight hours. ${used} hours have elapsed since the last inspection. How many hours remain before the scheduled inspection?`,`${remain} h`,[`${used} h`,`${interval+used} h`,`${Math.abs(interval-2*used)} h`],`Remaining time is interval minus elapsed time: ${interval}-${used}=${remain} h.`,'inspection-remaining')}
function genM8(){let k=ri(1,3);if(k===1){let rho=1.225,v=pick([30,40,50,60]),q=.5*rho*v*v;return scenarioQ(8,'Basic Aerodynamics','Dynamic pressure',2,3,`At sea-level density 1.225 kg/m³, an aircraft moves at ${v} m/s. Approximately what dynamic pressure acts on the airflow?`,`${q.toFixed(0)} Pa`,[`${(rho*v).toFixed(0)} Pa`,`${(rho*v*v).toFixed(0)} Pa`,`${(.5*rho*v).toFixed(0)} Pa`],`Dynamic pressure q=½ρV²=0.5×1.225×${v}²≈${q.toFixed(0)} Pa.`,'dynamic-pressure')}
if(k===2){let lift=pick([12000,18000,24000]),area=pick([20,30,40]),load=lift/area;return scenarioQ(8,'Basic Aerodynamics','Wing loading',2,3,`A wing produces ${lift} N of lift over a planform area of ${area} m². What is the lift per unit area?`,`${load.toFixed(0)} N/m²`,[`${(lift*area).toFixed(0)} N/m²`,`${(area/lift).toFixed(4)} N/m²`,`${(load/2).toFixed(0)} N/m²`],`Lift per unit area=${lift}/${area}=${load.toFixed(0)} N/m².`,'lift-per-area')}
let v1=pick([40,50,60]),factor=pick([1.2,1.3,1.4]),v2=v1*factor;return scenarioQ(8,'Basic Aerodynamics','Speed relationships',2,3,`A reference speed is ${v1} kt. A procedure requires ${factor.toFixed(1)} times that speed. What target speed should be used?`,`${v2.toFixed(0)} kt`,[`${(v1+factor).toFixed(0)} kt`,`${(v1/factor).toFixed(0)} kt`,`${(v2+10).toFixed(0)} kt`],`Target speed=${v1}×${factor.toFixed(1)}=${v2.toFixed(0)} kt.`,'speed-factor')}
function genM9(){let duty=pick([8,10,12]),breaks=pick([1,2,3]),work=duty-breaks*.5;return scenarioQ(9,'Human Factors','Fatigue and workload',2,3,`A maintenance shift lasts ${duty} h and includes ${breaks} breaks of 30 minutes each. How much active duty time remains, assuming no other interruptions?`,`${work.toFixed(1)} h`,[`${(duty-breaks).toFixed(1)} h`,`${(duty+breaks*.5).toFixed(1)} h`,`${(breaks*.5).toFixed(1)} h`],`Total break time is ${breaks}×0.5=${(breaks*.5).toFixed(1)} h. Active duty=${duty}-${(breaks*.5).toFixed(1)}=${work.toFixed(1)} h.`,'shift-active-time')}
function genM10(){let due=pick([30,60,90,120]),elapsed=pick([10,20,25,40]),remain=due-elapsed;return scenarioQ(10,'Aviation Legislation','Continuing airworthiness records',2,3,`A controlled maintenance action must be completed within ${due} days from an approved reference date. ${elapsed} days have elapsed. Assuming no extension applies, how many days remain?`,`${remain} days`,[`${elapsed} days`,`${due+elapsed} days`,`${Math.abs(due-2*elapsed)} days`],`Remaining calendar time is ${due}-${elapsed}=${remain} days. The calculation does not change the applicable regulatory requirement.`,'compliance-window')}
function genM11(){let k=ri(1,3);if(k===1){let total=pick([4000,5000,6000]),fuel=pick([800,1000,1200]),burn=pick([200,300,400]),newm=total-burn;return scenarioQ(11,'Aeroplane Aerodynamics, Structures and Systems','Fuel system',3,3,`An aircraft has a mass of ${total} kg including ${fuel} kg of fuel. During a ground run ${burn} kg of fuel is consumed and no other mass changes occur. What is the new aircraft mass?`,`${newm} kg`,[`${total-fuel} kg`,`${total+burn} kg`,`${newm-fuel} kg`],`Only the consumed fuel changes mass: ${total}-${burn}=${newm} kg.`,'fuel-mass-change')}
if(k===2){let p=pick([180,200,220]),area=pick([20,25,30]),force=p*1000*(area/10000);return scenarioQ(11,'Aeroplane Aerodynamics, Structures and Systems','Hydraulics',3,3,`A hydraulic actuator is supplied at ${p} kPa and has an effective piston area of ${area} cm². Ignoring losses, approximately what force can it produce?`,`${force.toFixed(0)} N`,[`${(p*area).toFixed(0)} N`,`${(force/10).toFixed(0)} N`,`${(force*2).toFixed(0)} N`],`${p} kPa=${p*1000} Pa and ${area} cm²=${(area/10000).toFixed(4)} m². F=PA≈${force.toFixed(0)} N.`,'hydraulic-force')}
let cap=pick([20,30,40]),used=pick([5,8,10,12]),pct=(cap-used)/cap*100;return scenarioQ(11,'Aeroplane Aerodynamics, Structures and Systems','System capacity',3,2,`A system reservoir has a usable capacity of ${cap} L. After operation, ${used} L have been consumed. What percentage of usable capacity remains?`,`${pct.toFixed(0)}%`,[`${(used/cap*100).toFixed(0)}%`,`${(cap-used).toFixed(0)}%`,`${(pct/2).toFixed(0)}%`],`Remaining quantity=${cap}-${used}=${cap-used} L. Percentage remaining=(${cap-used}/${cap})×100=${pct.toFixed(0)}%.`,'reservoir-percent')}
function genM15(){let k=ri(1,3);if(k===1){let n1=pick([8000,10000,12000]),ratio=pick([3,4,5]),n2=n1/ratio;return scenarioQ(15,'Gas Turbine Engines','Gearboxes',3,3,`A turbine shaft rotates at ${n1} rpm and drives an accessory through a ${ratio}:1 reduction gearbox. Ignoring slip, what accessory speed results?`,`${n2.toFixed(0)} rpm`,[`${n1*ratio} rpm`,`${n1-ratio} rpm`,`${(n2*ratio/2).toFixed(0)} rpm`],`A ${ratio}:1 reduction divides input speed by ${ratio}: ${n1}/${ratio}=${n2.toFixed(0)} rpm.`,'gear-reduction')}
if(k===2){let pin=pick([1,1.2,1.5]),pr=pick([8,10,12]),pout=pin*pr;return scenarioQ(15,'Gas Turbine Engines','Compressors',3,3,`A compressor operates with an overall pressure ratio of ${pr}:1. If inlet total pressure is ${pin.toFixed(1)} bar, what idealized outlet total pressure corresponds to that ratio?`,`${pout.toFixed(1)} bar`,[`${(pr/pin).toFixed(1)} bar`,`${(pout-pin).toFixed(1)} bar`,`${(pin+pr).toFixed(1)} bar`],`Pressure ratio=Pout/Pin, so Pout=${pr}×${pin.toFixed(1)}=${pout.toFixed(1)} bar.`,'compressor-pressure-ratio')}
let flow=pick([0.4,0.5,0.6,0.8]),time=pick([10,15,20]),mass=flow*time;return scenarioQ(15,'Gas Turbine Engines','Fuel system',3,3,`During a test, fuel flow is steady at ${flow.toFixed(1)} kg/s for ${time} s. How much fuel is delivered?`,`${mass.toFixed(1)} kg`,[`${(flow/time).toFixed(2)} kg`,`${(mass*60).toFixed(1)} kg`,`${time.toFixed(1)} kg`],`Mass=mass flow×time=${flow.toFixed(1)}×${time}=${mass.toFixed(1)} kg.`,'fuel-flow-mass')}
function genM17(){let k=ri(1,3);if(k===1){let eng=pick([1800,2000,2200,2400]),ratio=pick([1.5,2,2.5]),prop=eng/ratio;return scenarioQ(17,'Propellers','Reduction gearing',3,3,`An engine runs at ${eng} rpm and the propeller reduction ratio is ${ratio}:1. What propeller speed is expected?`,`${prop.toFixed(0)} rpm`,[`${(eng*ratio).toFixed(0)} rpm`,`${(eng-ratio).toFixed(0)} rpm`,`${(prop/ratio).toFixed(0)} rpm`],`Propeller speed equals engine speed divided by the reduction ratio: ${eng}/${ratio}=${prop.toFixed(0)} rpm.`,'prop-reduction')}
if(k===2){let dia=pick([1.8,2.0,2.2,2.4]),r=dia/2,area=Math.PI*r*r;return scenarioQ(17,'Propellers','Propeller geometry',2,3,`A propeller has a diameter of ${dia.toFixed(1)} m. Approximately what disc area does it sweep?`,`${area.toFixed(2)} m²`,[`${(Math.PI*dia).toFixed(2)} m²`,`${(dia*dia).toFixed(2)} m²`,`${(area/2).toFixed(2)} m²`],`Disc area=πr² with r=${r.toFixed(2)} m, giving approximately ${area.toFixed(2)} m².`,'prop-disc-area')}
let rpm=pick([1200,1500,1800]),sec=pick([10,20,30]),rev=rpm*sec/60;return scenarioQ(17,'Propellers','Rotational speed',2,3,`A propeller turns at ${rpm} rpm for ${sec} seconds during a ground check. Approximately how many revolutions does it complete?`,`${rev.toFixed(0)} revolutions`,[`${rpm*sec} revolutions`,`${(rpm/sec).toFixed(0)} revolutions`,`${(rev/2).toFixed(0)} revolutions`],`${rpm} rpm=${rpm/60} revolutions per second. Over ${sec} s it completes ${rev.toFixed(0)} revolutions.`,'prop-revolutions')}


function genM12(){let rpm=pick([300,360,420]),sec=pick([10,15,20]),rev=rpm*sec/60;return scenarioQ(12,'Helicopter Aerodynamics, Structures and Systems','Rotor speed',2,3,`A main rotor turns at ${rpm} RPM. Approximately how many revolutions does it complete in ${sec} seconds?`,`${rev.toFixed(0)} revolutions`,[`${(rpm*sec).toFixed(0)} revolutions`,`${(rpm/sec).toFixed(0)} revolutions`,`${(rev/2).toFixed(0)} revolutions`],`Revolutions = RPM × time/60 = ${rpm} × ${sec}/60 = ${rev.toFixed(0)}.`,'rotor-rpm-time')}
function genM13(){let f=pick([108.0,110.0,112.0]),mhz=pick([2,3,4]),upper=f+mhz/10;return scenarioQ(13,'Aircraft Aerodynamics, Structures and Systems','Avionics frequency reasoning',3,3,`A navigation receiver is tuned to ${f.toFixed(1)} MHz and is retuned upward by ${(mhz/10).toFixed(1)} MHz. What is the new frequency?`,`${upper.toFixed(1)} MHz`,[`${(f-mhz/10).toFixed(1)} MHz`,`${(f+mhz).toFixed(1)} MHz`,`${(upper+0.5).toFixed(1)} MHz`],`New frequency = ${f.toFixed(1)} + ${(mhz/10).toFixed(1)} = ${upper.toFixed(1)} MHz.`,'nav-frequency')}
function genM14(){let mdot=pick([20,25,30]),dv=pick([100,120,150]),thrust=mdot*dv;return scenarioQ(14,'Propulsion','Momentum thrust',2,3,`Ignoring pressure thrust, an engine accelerates ${mdot} kg/s of airflow by ${dv} m/s. What approximate thrust results?`,`${thrust} N`,[`${mdot+dv} N`,`${(thrust/10).toFixed(0)} N`,`${mdot*dv*2} N`],`Thrust from momentum change is approximately ṁΔV = ${mdot} × ${dv} = ${thrust} N.`,'momentum-thrust')}
function genM18(){let v=pick([300,400,500]),i=pick([80,100,120,150]),p=v*i/1000;return scenarioQ(18,'Electric Power Plant','Electrical propulsion power',2,3,`An electric propulsion system operates at ${v} V DC and draws ${i} A. Ignoring conversion losses, what electrical input power is being supplied?`,`${p.toFixed(1)} kW`,[`${(v/i).toFixed(1)} kW`,`${(v+i).toFixed(1)} kW`,`${(p/10).toFixed(1)} kW`],`Electrical power is P = V × I. ${v} × ${i} = ${v*i} W = ${p.toFixed(1)} kW.`,'electric-propulsion-power')}
function genM16(){let swept=pick([360,420,480]),clear=pick([60,70,80]),cr=(swept+clear)/clear;return scenarioQ(16,'Piston Engines','Compression ratio',2,3,`A piston-engine cylinder has a swept volume of ${swept} cm³ and a clearance volume of ${clear} cm³. What is the compression ratio?`,`${cr.toFixed(1)}:1`,[`${(swept/clear).toFixed(1)}:1`,`${((swept-clear)/clear).toFixed(1)}:1`,`${((swept+clear)/swept).toFixed(1)}:1`],`Compression ratio = (swept + clearance) / clearance = (${swept}+${clear})/${clear} = ${cr.toFixed(1)}:1.`,'compression-ratio-calc')}
function genL(m){
 let k=String(m);
 if(k==='1L'){let v=pick([12,24,28]),i=pick([2,3,4,5]),p=v*i;return scenarioQ('1L','Basic Knowledge','Electrical basics',2,2,`A ${v} V circuit supplies ${i} A to an aircraft component. What electrical power is being used?`,`${p} W`,[`${v+i} W`,`${(v/i).toFixed(1)} W`,`${p*2} W`],`Power is voltage multiplied by current: ${v} × ${i} = ${p} W.`,'L-basic-power')}
 if(k==='2L'){let shift=pick([8,10,12]),br=pick([30,45,60]),active=shift-br/60;return scenarioQ('2L','Human Factors','Fatigue and workload',2,2,`A maintenance duty period is ${shift} hours with a ${br}-minute rest break. Ignoring other interruptions, how much active duty time remains?`,`${active.toFixed(2)} h`,[`${(shift-br/100).toFixed(2)} h`,`${(shift+br/60).toFixed(2)} h`,`${(br/60).toFixed(2)} h`],`Convert the break to hours and subtract it from the duty period: ${shift} − ${br}/60 = ${active.toFixed(2)} h.`,'L-human-duty')}
 if(k==='3L'){let total=pick([30,60,90]),elapsed=pick([10,15,20]),remain=total-elapsed;return scenarioQ('3L','Aviation Legislation','Compliance planning',2,2,`A maintenance action has an approved interval of ${total} days and ${elapsed} days have elapsed. With no extension applied, how many days remain?`,`${remain} days`,[`${elapsed} days`,`${total+elapsed} days`,`${total} days`],`The remaining interval is ${total} − ${elapsed} = ${remain} days.`,'L-leg-window')}
 if(k==='4L'){let load=pick([600,800,1000]),n=pick([2,4,5]),each=load/n;return scenarioQ('4L','Wooden / Metal-Tube & Fabric Structure','Load distribution',2,3,`A fabric-covered structural attachment distributes a ${load} N load equally across ${n} identical approved attachment points. What load acts at each point?`,`${each.toFixed(0)} N`,[`${load*n} N`,`${(load/(n+1)).toFixed(0)} N`,`${(load-n).toFixed(0)} N`],`For equal load sharing, divide the total load by ${n}: ${load}/${n} = ${each.toFixed(0)} N.`,'L4-load-share')}
 if(k==='5L'){let mass=pick([2,3,4]),resin=pick([35,40,45]),r=mass*resin/100;return scenarioQ('5L','Composite Structure','Composite materials',2,3,`A composite repair mix has a total mass of ${mass} kg and requires ${resin}% resin by mass. How much resin is required?`,`${r.toFixed(2)} kg`,[`${(mass-r).toFixed(2)} kg`,`${(resin/mass).toFixed(2)} kg`,`${(mass*resin).toFixed(0)} kg`],`Required resin mass is ${mass} × ${resin}/100 = ${r.toFixed(2)} kg.`,'L5-resin')}
 if(k==='6L'){let d=pick([4,5,6,8]),a=Math.PI*d*d/4;return scenarioQ('6L','Metallic Structure','Fastener inspection',2,3,`A circular metallic fastener has a shank diameter of ${d} mm. Approximately what is its cross-sectional area?`,`${a.toFixed(1)} mm²`,[`${(Math.PI*d).toFixed(1)} mm²`,`${(d*d).toFixed(1)} mm²`,`${(a/2).toFixed(1)} mm²`],`Cross-sectional area is πd²/4, giving approximately ${a.toFixed(1)} mm².`,'L6-fastener-area')}
 if(k==='7L'){let cap=pick([12,18,24]),used=pick([3,6,9]),rem=cap-used;return scenarioQ('7L','Airframe – General, Mechanical & Electrical Systems','Consumables planning',2,2,`A maintenance task starts with ${cap} litres of approved fluid and uses ${used} litres. How much remains?`,`${rem} L`,[`${cap+used} L`,`${used} L`,`${cap} L`],`Remaining quantity is ${cap} − ${used} = ${rem} L.`,'L7-fluid')}
 if(k==='8L'){let rpm=pick([2400,2700,3000]),ratio=pick([1.5,2,2.5]),out=rpm/ratio;return scenarioQ('8L','Power Plant','Reduction drive',2,3,`A light-aircraft engine runs at ${rpm} rpm through a ${ratio}:1 reduction drive. What is the approximate output speed?`,`${out.toFixed(0)} rpm`,[`${(rpm*ratio).toFixed(0)} rpm`,`${(rpm-ratio).toFixed(0)} rpm`,`${(out/ratio).toFixed(0)} rpm`],`A reduction ratio divides input speed: ${rpm}/${ratio} = ${out.toFixed(0)} rpm.`,'L8-reduction')}
 if(k==='9L'){let vol=pick([1800,2200,2600]),rise=pick([5,10,15]),newv=vol*(1+rise/100);return scenarioQ('9L','Hot-Air Balloons','Envelope volume reasoning',2,3,`For a simplified training calculation, a hot-air balloon envelope volume of ${vol} m³ increases by ${rise}%. What is the resulting volume?`,`${newv.toFixed(0)} m³`,[`${(vol+rise).toFixed(0)} m³`,`${(vol*(1-rise/100)).toFixed(0)} m³`,`${(vol*rise).toFixed(0)} m³`],`A ${rise}% increase gives ${vol} × (1 + ${rise}/100) = ${newv.toFixed(0)} m³.`,'L9-volume')}
 if(k==='10L'){let p=pick([100,120,150]),pct=pick([5,10,20]),newp=p*(1+pct/100);return scenarioQ('10L','Gas Balloons','Gas pressure reasoning',2,3,`In a simplified maintenance calculation, a gas-system pressure of ${p} kPa increases by ${pct}%. What pressure results?`,`${newp.toFixed(0)} kPa`,[`${p+pct} kPa`,`${(p*(1-pct/100)).toFixed(0)} kPa`,`${p*pct} kPa`],`Apply the percentage increase: ${p} × (1 + ${pct}/100) = ${newp.toFixed(0)} kPa.`,'L10-pressure')}
 if(k==='11L'){let speed=pick([40,50,60]),time=pick([2,3,4]),dist=speed*time;return scenarioQ('11L','Airships – Hot-Air / Gas','Ground handling planning',2,2,`For a planning exercise, an airship ground-handling vehicle travels at ${speed} m/min for ${time} minutes. What distance does it cover?`,`${dist} m`,[`${speed+time} m`,`${(speed/time).toFixed(1)} m`,`${dist*2} m`],`Distance equals speed × time: ${speed} × ${time} = ${dist} m.`,'L11-distance')}
 if(k==='12L'){let mhz=pick([121.5,123.5,125.0]),delta=pick([0.1,0.2,0.5]),f=mhz+delta;return scenarioQ('12L','Radio Com / ELT / Transponder / Instruments','Frequency setting',2,2,`A receiver is set to ${mhz.toFixed(1)} MHz and retuned upward by ${delta.toFixed(1)} MHz. What is the new setting?`,`${f.toFixed(1)} MHz`,[`${(mhz-delta).toFixed(1)} MHz`,`${(mhz+delta*10).toFixed(1)} MHz`,`${delta.toFixed(1)} MHz`],`Add the frequency change: ${mhz.toFixed(1)} + ${delta.toFixed(1)} = ${f.toFixed(1)} MHz.`,'L12-frequency')}
 return null;
}
function generateDynamicForModule(m){if(String(m).endsWith('L'))return genL(String(m));m=Number(m);if(m===1)return genMath();if(m===2)return genPhysics();if(m===3)return genElectrical();if(m===4)return genM4();if(m===5)return genM5();if(m===6)return genM6();if(m===7)return genM7();if(m===8)return genM8();if(m===9)return genM9();if(m===10)return genM10();if(m===11)return genM11();if(m===12)return genM12();if(m===13)return genM13();if(m===14)return genM14();if(m===15)return genM15();if(m===16)return genM16();if(m===17)return genM17();if(m===18)return genM18();return null}
function dynamicSession(count,module=null){let out=[],guard=0;while(out.length<count&&guard++<count*20){let m=module?module:pick(activeMods());let q=generateDynamicForModule(m);if(q){let sig=q.question+'|'+q.answers.join('|');if(!out.some(x=>x.question===q.question)&&!dynHistory().some(h=>h.sig===sig)){out.push(q);saveDynHistory(sig)}}}return out}
function variedStaticPool(items,n){let recent=new Set(dynHistory().slice(0,120).map(x=>x.sig));let weighted=shuffle(uniqueConcepts(items)).sort((a,b)=>{let ar=S.stats[a.id]?.lastSeen||0,br=S.stats[b.id]?.lastSeen||0;return ar-br});let chosen=weighted.slice(0,n).map(q=>{let ans=q.answers.map((x,i)=>({x,i})),sh=shuffle(ans);return {...q,answers:sh.map(z=>z.x),correct:sh.findIndex(z=>z.i===q.correct)}});chosen.forEach(q=>saveDynHistory(`STATIC|${q.id}|${q.answers.join('|')}`));return chosen}
function buildDynamicQuiz(count=SETTINGS.length,module=null){let dynamicCount=Math.max(1,Math.round(count*.65));let dyn=dynamicSession(dynamicCount,module);let source=module?activeQuestions().filter(q=>String(q.module)===String(module)):activeQuestions();let stat=variedStaticPool(source,Math.max(0,count-dyn.length));return shuffle([...dyn,...stat]).slice(0,count)}
// Override quiz entry points with session-varying engine.
startQuiz=function(){start(buildDynamicQuiz(SETTINGS.length),`Dynamic quiz • new session`,false)};
startModule=function(n){let source=activeQuestions().filter(q=>String(q.module)===String(n)),count=Math.min(Math.max(10,SETTINGS.length),source.length||SETTINGS.length);let items=buildDynamicQuiz(count,n);start(items,`${String(n).endsWith('L')?n:'M'+n} – ${MODS[n]} • dynamic session`,false)};
window.startQuiz=startQuiz;window.startModule=startModule;
